# Generated by Django 4.0 on 2021-12-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='path',
            field=models.FilePathField(default='C:\\Users\\PC\\PycharmProjects\\upload_csv_project\\uploading_csv_project\\media', path='C:\\Users\\PC\\PycharmProjects\\upload_csv_project\\uploading_csv_project\\media'),
        ),
    ]
